# Generated by Django 5.0.6 on 2024-06-19 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Facilitator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('facilitates', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('lessons', models.TextField()),
                ('learning_outcomes', models.TextField()),
                ('facilitators', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreams.facilitator')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreams.event')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreams.material')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('has_hiv', models.BooleanField()),
                ('education', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('enrollment_date', models.DateField()),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreams.agegroup')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantEventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField()),
                ('lessons_attended', models.IntegerField(default=0)),
                ('finished_program', models.BooleanField(default=False)),
                ('self_sufficient', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreams.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreams.participant')),
            ],
        ),
    ]
