# Generated by Django 5.0.6 on 2024-06-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='facilitators',
        ),
        migrations.AddField(
            model_name='event',
            name='facilitators',
            field=models.ManyToManyField(to='dreams.facilitator'),
        ),
    ]
