# Generated by Django 5.0.6 on 2024-06-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0002_remove_event_facilitators_event_facilitators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='education',
        ),
        migrations.AddField(
            model_name='participant',
            name='is_in_school',
            field=models.BooleanField(default=False),
        ),
    ]
